BEGIN;

DROP TABLE IF EXISTS availability CASCADE;
DROP TABLE IF EXISTS competence_profile CASCADE;
DROP TABLE IF EXISTS application CASCADE;
DROP TABLE IF EXISTS auth_recovery_token CASCADE;
DROP TABLE IF EXISTS user_account CASCADE;
DROP TABLE IF EXISTS competence CASCADE;
DROP TABLE IF EXISTS person CASCADE;
DROP TABLE IF EXISTS schema_migrations CASCADE;
DROP TABLE IF EXISTS event_log CASCADE;
DROP SCHEMA IF EXISTS legacy CASCADE;
COMMIT;
